version: '3.7'

services:
    geoweb-backend:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: geoweb-backend:latest
        ports:
            - "8091:8080"
        volumes:
            - /var/opt/geoweb/geoweb-backend/tmp/tafs:/tmp/tafs
            - /var/opt/geoweb/geoweb-backend/tmp/sigmets:/tmp/sigmets
            - /var/opt/geoweb/geoweb-backend/tmp/presets:/tmp/presets
            - /var/opt/geoweb/geoweb-backend/tmp/airmets:/tmp/airmets
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3
    geoweb-frontend-nginx:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: geoweb-frontend-nginx:latest
        depends_on:
            - "geoweb-backend"
        ports:
            - "8090:80"
        environment:
            - "GEOWEBBACKENDURL=http://spiritus:8091/backend"
            - "WEBSERVER_URL=http://spiritus:8090"
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3
    adaguc-db:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: postgres:latest
        environment:
            - "POSTGRES_USER=adaguc"
            - "POSTGRES_PASSWORD=adaguc"
            - "POSTGRES_DB=adaguc"
        logging:
              driver: "json-file"
              options:
                max-size: "200k"
                max-file: "10"
        healthcheck:
            # Disabled for now because for some reason
            # using this healthcheck makes swarm loose
            # adaguc-db hostname information that
            # adaguc-server needs for postgres connection.
            disable: true
            #test: ["CMD", "pg_isready -U postgres"]
            interval: 1m
            timeout: 10s
            retries: 3
    adaguc-server:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: adaguc-server:latest
        depends_on:
            - "adaguc-db"
        volumes:
            - /var/opt/geoweb/adaguc-server/data/adaguc-datasets:/data/adaguc-datasets
            - /var/opt/geoweb/adaguc-server/data/adaguc-autowms:/data/adaguc-autowms
            - /var/opt/geoweb/adaguc-server/data/adaguc-data:/data/adaguc-data
            - /var/opt/geoweb/adaguc-server/log:/var/log/adaguc
            - /var/opt/geoweb/adaguc-server/adagucdb:/adaguc/adagucdb
            - /var/opt/geoweb/adaguc-server/security:/adaguc/security
        ports:
            - "8093:8080"
        environment:
            - "EXTERNALADDRESS=http://spiritus:8093"
            - "ADAGUC_DB=host=adaguc-db port=5432 user=adaguc password=adaguc dbname=adaguc"
            - "ADAGUC_SERVICES_CONFIG=/adaguc/adaguc-services-config.xml"
        logging:
              driver: "json-file"
              options:
                max-size: "200k"
                max-file: "10"
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3
    adaguc-viewer:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: adaguc-viewer:latest
        depends_on:
            - "adaguc-server"
        ports:
            - "8092:80"
        environment:
            - "EXTERNALADDRESS=http://spiritus:8092"
            - "LOCAL_ADAGUCSERVER_ADDR=http://spiritus:8093" # Should be same as adaguc-server's EXTERNALADDRESS
            - "REMOTE_ADAGUCSERVER_ADDR=http://spiritus:8093" # Do not change this within the docker-compose environment
            - "ADAGUCSERVICES_AUTOWMS=http://spiritus:8093/adaguc-services/autowms?"
        logging:
              driver: "json-file"
              options:
                max-size: "200k"
                max-file: "10"
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3


# Visit http://localhost:8090 for GeoWeb-FrontEnd
# Visit http://localhost:8092 for adaguc-viewer
