version: '2'

services:
    geoweb-backend:
        image: geoweb-backend
        container_name: geoweb-backend
        ports:
            - "8091:8080"
        volumes:
            - /var/opt/geoweb/geoweb-backend/tmp/tafs:/tmp/tafs
            - /var/opt/geoweb/geoweb-backend/tmp/sigmets:/tmp/sigmets
            - /var/opt/geoweb/geoweb-backend/tmp/presets:/tmp/presets
            - /var/opt/geoweb/geoweb-backend/tmp/airmets:/tmp/airmets
    geoweb-frontend-nginx :
        image: geoweb-frontend-nginx
        container_name: geoweb-frontend-nginx
        ports:
            - "8090:80"
        environment:
            - "GEOWEBBACKENDURL=http://spiritus:8091/backend"
            - "WEBSERVER_URL=http://spiritus:8090"
    adaguc-server:
        image: adaguc-server
        container_name: adaguc-server
        ports:
            - "8093:8080"
        volumes:
            - /var/opt/geoweb/adaguc-server/data/adaguc-datasets:/data/adaguc-datasets
            - /var/opt/geoweb/adaguc-server/data/adaguc-autowms:/data/adaguc-autowms
            - /var/opt/geoweb/adaguc-server/data/adaguc-data:/data/adaguc-data
            - /var/opt/geoweb/adaguc-server/log:/var/log/adaguc
            - /var/opt/geoweb/adaguc-server/adagucdb:/adaguc/adagucdb
            - /var/opt/geoweb/adaguc-server/security:/adaguc/security
        environment:
            - "EXTERNALADDRESS=http://spiritus:8093"
    adaguc-viewer:
        image: adaguc-viewer
        container_name: adaguc-viewer
        ports:
            - "8092:80"

# Visit http://localhost:8090 for GeoWeb-FrontEnd
