version: '3.2'

services:
    geoweb-backend:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: geoweb-backend:latest
        ports:
            - "8091:8080"
        volumes:
            - /var/opt/geoweb/geoweb-backend/tmp/tafs:/tmp/tafs
            - /var/opt/geoweb/geoweb-backend/tmp/sigmets:/tmp/sigmets
            - /var/opt/geoweb/geoweb-backend/tmp/presets:/tmp/presets
            - /var/opt/geoweb/geoweb-backend/tmp/airmets:/tmp/airmets
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3
    geoweb-frontend-nginx:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: geoweb-frontend-nginx:latest
        ports:
            - "8090:80"
        environment:
            - "GEOWEBBACKENDURL=http://spiritus:8091/backend"
            - "WEBSERVER_URL=http://spiritus:8090"
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3
    adaguc-server:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: adaguc-server:latest
        ports:
            - "8093:8080"
        volumes:
            - /var/opt/geoweb/adaguc-server/data/adaguc-datasets:/data/adaguc-datasets
            - /var/opt/geoweb/adaguc-server/data/adaguc-autowms:/data/adaguc-autowms
            - /var/opt/geoweb/adaguc-server/data/adaguc-data:/data/adaguc-data
            - /var/opt/geoweb/adaguc-server/log:/var/log/adaguc
            - /var/opt/geoweb/adaguc-server/adagucdb:/adaguc/adagucdb
            - /var/opt/geoweb/adaguc-server/security:/adaguc/security
        environment:
            - "EXTERNALADDRESS=http://spiritus:8093"
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3
    adaguc-viewer:
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
        image: adaguc-viewer:latest
        ports:
            - "8092:80"
	environment:
            - "ADAGUCSERVICES_AUTOWMS=http://spiritus:8090/adaguc-services/autowms?"
        healthcheck:
            test: ["CMD", "/opt/healthcheck.sh"]
            interval: 1m
            timeout: 10s
            retries: 3


# Visit http://localhost:8090 for GeoWeb-FrontEnd
# Visit http://localhost:8092 for adaguc-viewer
